---
name: Molecule
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  molecule:
    runs-on: ubuntu-latest
    env:
      DOCKER_USER: ${{ github.actor }}
      DOCKER_PW: ${{ secrets.GITHUB_TOKEN }}
      DOCKER_REGISTRY: ghcr.io
      ANSIBLE_FORCE_COLOR: '1'
      REQUIREMENTS_FILE: ext/molecule-src/requirements.txt
      MOLECULE_FILE: ext/molecule-src/molecule.yml
    strategy:
      fail-fast: false
      matrix:
        catalog_items:
          - python-workbench
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install -r ${{ env.REQUIREMENTS_FILE }}
      - name: Molecule tests
        run: |
          cd ${{ matrix.catalog_items }}
          molecule -c ../{{ env.MOLECULE_FILE }} test --all
